name: check_vpn_connection
description: A simple and lightweight Flutter package that lets you define VPN connection status on your devices.
version: 0.0.2
homepage: https://github.com/RenatFakhrutdinov/check_vpn_connection/

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: